# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{html_page_title}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Olszowka"]
  s.date = %q{2010-07-15}
  s.description = %q{Retrieve the page title for a given url using redirect_follower and hpricot ruby gems}
  s.email = %q{'christoph at olszowka.de'}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "html_page_title.gemspec",
     "lib/html_page_title.rb",
     "test/helper.rb",
     "test/test_html_page_title.rb"
  ]
  s.homepage = %q{http://github.com/colszowka/html_page_title}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Retrieve the page title for a given url (including redirects)}
  s.test_files = [
    "test/helper.rb",
     "test/test_html_page_title.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redirect_follower>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8.2"])
      s.add_development_dependency(%q<shoulda>, [">= 2.11.1"])
    else
      s.add_dependency(%q<redirect_follower>, [">= 0.1.1"])
      s.add_dependency(%q<hpricot>, [">= 0.8.2"])
      s.add_dependency(%q<shoulda>, [">= 2.11.1"])
    end
  else
    s.add_dependency(%q<redirect_follower>, [">= 0.1.1"])
    s.add_dependency(%q<hpricot>, [">= 0.8.2"])
    s.add_dependency(%q<shoulda>, [">= 2.11.1"])
  end
end

